pull_request_rules:
  - name: backport master patches to 20.08 branch
    conditions:
      - base=master
      - label=backport-to-20.08
    actions:
      backport:
        branches:
          - gvmd-20.08

  - name: backport 20.08 patches to master branch
    conditions:
      - base=gvmd-20.08
      - label=backport-to-master
    actions:
      backport:
        branches:
          - master
